@isTest
public class GoikenContrllerTest {
    /*@isTest
    static void testmethod1() {
        PageReference pref = Page.Goiken;
        Test.setCurrentPage(pref);
        GoikenController goiken = new GoikenController();
        Test.startTest();
        PageReference pr = goiken.input();
        Test.stopTest();
        System.assertEquals('/apex/goiken', pr.getUrl());
    }
    @isTest
    static void testmethod2() {
        PageReference pref = Page.Goiken;
        Test.setCurrentPage(pref);
        GoikenController goiken = new GoikenController();
        Test.startTest();
        PageReference pr = goiken.confirm();
        Test.stopTest();
        System.assertEquals('/apex/goikenconfirm', pr.getUrl());
    }

    @isTest
    static void testmethod4() {
        case form = new case();
        form.Subject = 'object';
        form.Opinion__c = 'opinion';
        form.EasyToUnderstand__c = '分かりやすい';
        form.EaseOfApplication__c = '申請しやすい';
        form.SiteDesign__c = '分かりやすい';
        insert form;
        PageReference pref = Page.Goiken;
        Test.setCurrentPage(pref);
        Test.startTest();
        GoikenController goiken = new GoikenController();
        PageReference pr = goiken.submit();
        Test.stopTest();
        System.assertEquals('object', form.Subject);
        System.assertEquals('opinion', form.Opinion__c);
        System.assertEquals('分かりやすい', form.EasyToUnderstand__c);
        System.assertEquals('申請しやすい', form.EaseOfApplication__c);
        System.assertEquals('分かりやすい', form.SiteDesign__c);
    }*/
}